icons_format = "{icon}"

#[theme]
#theme = "solarized-dark"
#[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"
#theme = "gruvbox-dark"
[theme]
theme = "srcery"
#theme = "plain"
[theme.overrides]
idle_bg = "#007c93"
idle_fg = "#fcfcfb"
info_bg = "#1f8498" # the music block bg
info_fg = "#fceedd" # the music block fg
good_bg = "#a26055" # battery block bg
good_fg = "#fceedd" # battery block fg
warning_bg = "#d79921"
warning_fg = "#fbf1c7"
critical_bg = "#fceedd"
critical_fg = "#a26055"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"

[icons]
icons = "awesome4"
[icons.overrides]
#bat = ["|E|", "|_|", "|=|", "|F|"]
#bat_charging = "|^|"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:15) |"
short = " $title.str(max_w:10) |"

#[[block]]
#block = "net"
#format = " $icon {$ssid |}^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "
#device = "wlp0s20f3"

[[block]]
block = "menu"
text = " \uf011 "
[[block.items]]
display = " -&gt; Power Off &lt;-"
cmd = "poweroff"
confirm_msg = " Are you sure you want to power off? "
[[block.items]]
display = " -&gt;  Reboot   &lt;-"
cmd = "reboot"
confirm_msg = " Are you sure you want to reboot? "

[[block]]
block = "bluetooth"
mac = "4C:87:5D:A3:C6:90"
disconnected_format = ""
format = " $icon "

#[[block]]
#block = "battery"
#interval = 30
#format = "{percentage}% {time}"
#device = 'BAT1'
#driver = "upower"
#good = 101
#info = 70
#warning = 50
#critical = 30

[[block]]
block = "battery"
interval = 30
full_format = " $icon $percentage "
device = 'BAT0'
driver = "upower"

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "

[[block]]
block = "temperature"
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
scale = "celsius"
interval = 10
chip = "*-isa-*"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
